import React from 'react'
import * as Icons from "react-icons/fa";

const CLOSINFO = () => {
  return (
    <>
    <h1 className='h1 my-2 text-center'>
        Courses Learning Outcomes Information of BS Computer Science
      </h1>
      <div className="container">
        <div className="clos">
          <table className="table">
            <thead>
              <tr>
                <th rowSpan={3}># </th>
                <th rowSpan={3}>Course Title</th>
                <th colSpan={19}>Learning Domains and Taxonomy Levels</th>
              </tr>
              <tr>
                <th colSpan={6}>Cognitive</th>
                <th colSpan={7}>Psychomotor</th>
                <th colSpan={5}>Affective</th>
                <th rowSpan={2}>Taxonomy Mapped</th>
              </tr>
              <tr>
                <th>C1</th>
                <th>C2</th>
                <th>C3</th>
                <th>C4</th>
                <th>C5</th>
                <th>C6</th>
                <th>P1</th>
                <th>P2</th>
                <th>P3</th>
                <th>P4</th>
                <th>P5</th>
                <th>P6</th>
                <th>P7</th>
                <th>A1</th>
                <th>A2</th>
                <th>A3</th>
                <th>A4</th>
                <th>A5</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>1</td>
                <td>Introduction to ICT</td>
                <td></td>
                <td><Icons.FaCheck/></td>
                <td><Icons.FaCheck/></td>
                <td></td>
                <td></td>
                <td></td>
                <td><Icons.FaCheck/></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td>3</td>
              </tr>
              <tr>
                <td>2</td>
                <td>Programming Fundamentals</td>
                <td></td>
                <td><Icons.FaCheck/></td>
                <td><Icons.FaCheck/></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td><Icons.FaCheck/></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td>3</td>
              </tr>
              <tr>
                <td>3</td>
                <td>Eng Composition & Comprehension</td>
                <td><Icons.FaCheck/></td>
                <td><Icons.FaCheck/></td>
                <td><Icons.FaCheck/></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td><Icons.FaCheck/></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td>4</td>
              </tr>
              <tr>
                <td>4</td>
                <td>Calculus & Analytical Geometry</td>
                <td><Icons.FaCheck/></td>
                <td><Icons.FaCheck/></td>
                <td><Icons.FaCheck/></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td>3</td>
              </tr>
              <tr>
                <td>5</td>
                <td>Applied Physics</td>
                <td></td>
                <td><Icons.FaCheck/></td>
                <td><Icons.FaCheck/></td>
                <td></td>
                <td></td>
                <td></td>
                <td><Icons.FaCheck/></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td>3</td>
              </tr>
              <tr>
                <td>6</td>
                <td>Digital Logic Design</td>
                <td><Icons.FaCheck/></td>
                <td><Icons.FaCheck/></td>
                <td><Icons.FaCheck/></td>
                <td><Icons.FaCheck/></td>
                <td></td>
                <td></td>
                <td><Icons.FaCheck/></td>
                <td><Icons.FaCheck/></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td>6</td>
              </tr>
              <tr>
                <td>7</td>
                <td>Object Oriented Porgramming</td>
                <td></td>
                <td><Icons.FaCheck/></td>
                <td><Icons.FaCheck/></td>
                <td><Icons.FaCheck/></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td>3</td>
              </tr>
              <tr>
                <td>8</td>
                <td>Communication & Presentaions Skills</td>
                <td><Icons.FaCheck/></td>
                <td><Icons.FaCheck/></td>
                <td><Icons.FaCheck/></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td>3</td>
              </tr>
              <tr>
                <td>9</td>
                <td>Probability & Statistics</td>
                <td><Icons.FaCheck/></td>
                <td><Icons.FaCheck/></td>
                <td><Icons.FaCheck/></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td><Icons.FaCheck/></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td>4</td>
              </tr>
              <tr>
                <td>10</td>
                <td>Introduction to Economics</td>
                <td><Icons.FaCheck/></td>
                <td><Icons.FaCheck/></td>
                <td><Icons.FaCheck/></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td><Icons.FaCheck/></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td>4</td>
              </tr>
              <tr>
                <td>11</td>
                <td>CO & Assembly Language</td>
                <td></td>
                <td><Icons.FaCheck/></td>
                <td><Icons.FaCheck/></td>
                <td><Icons.FaCheck/></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td>3</td>
              </tr>
              <tr>
                <td>12</td>
                <td>Data Structures & Algorithms</td>
                <td></td>
                <td><Icons.FaCheck/></td>
                <td><Icons.FaCheck/></td>
                <td><Icons.FaCheck/></td>
                <td><Icons.FaCheck/></td>
                <td><Icons.FaCheck/></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td>5</td>
              </tr>
              <tr>
                <td>13</td>
                <td>Discrete Structures</td>
                <td></td>
                <td><Icons.FaCheck/></td>
                <td><Icons.FaCheck/></td>
                <td><Icons.FaCheck/></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td>3</td>
              </tr>
              <tr>
                <td>14</td>
                <td>Professional Practices</td>
                <td><Icons.FaCheck/></td>
                <td><Icons.FaCheck/></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td><Icons.FaCheck/></td>
                <td><Icons.FaCheck/></td>
                <td></td>
                <td><Icons.FaCheck/></td>
                <td></td>
                <td>5</td>
              </tr>
              <tr>
                <td>15</td>
                <td>Diffenrential Equation</td>
                <td></td>
                <td><Icons.FaCheck/></td>
                <td><Icons.FaCheck/></td>
                <td><Icons.FaCheck/></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td>3</td>
              </tr>
              <tr>
                <td>16</td>
                <td>Design & Analysis of Algorithm</td>
                <td></td>
                <td><Icons.FaCheck/></td>
                <td><Icons.FaCheck/></td>
                <td><Icons.FaCheck/></td>
                <td><Icons.FaCheck/></td>
                <td><Icons.FaCheck/></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td>5</td>
              </tr>
              <tr>
                <td>17</td>
                <td>Theory of Automata</td>
                <td><Icons.FaCheck/></td>
                <td><Icons.FaCheck/></td>
                <td><Icons.FaCheck/></td>
                <td><Icons.FaCheck/></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td>4</td>
              </tr>
              <tr>
                <td>18</td>
                <td>Database Systems</td>
                <td></td>
                <td><Icons.FaCheck/></td>
                <td></td>
                <td><Icons.FaCheck/></td>
                <td><Icons.FaCheck/></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td>3</td>
              </tr>
              <tr>
                <td>19</td>
                <td>Linear Algebra</td>
                <td><Icons.FaCheck/></td>
                <td><Icons.FaCheck/></td>
                <td><Icons.FaCheck/></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td>3</td>
              </tr>
              <tr>
                <td>20</td>
                <td>Introduction to Accounting</td>
                <td><Icons.FaCheck/></td>
                <td><Icons.FaCheck/></td>
                <td><Icons.FaCheck/></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td>3</td>
              </tr>
              <tr>
                <td>21</td>
                <td>Compiler Contruction</td>
                <td></td>
                <td><Icons.FaCheck/></td>
                <td><Icons.FaCheck/></td>
                <td><Icons.FaCheck/></td>
                <td><Icons.FaCheck/></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td>4</td>
              </tr>
              <tr>
                <td>22</td>
                <td>Multi-variable Calculus</td>
                <td></td>
                <td><Icons.FaCheck/></td>
                <td><Icons.FaCheck/></td>
                <td><Icons.FaCheck/></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td>3</td>
              </tr>
              <tr>
                <td>23</td>
                <td>Operating Systems</td>
                <td></td>
                <td><Icons.FaCheck/></td>
                <td><Icons.FaCheck/></td>
                <td><Icons.FaCheck/></td>
                <td><Icons.FaCheck/></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td>4</td>
              </tr>
              <tr>
                <td>24</td>
                <td>Software Engineering</td>
                <td><Icons.FaCheck/></td>
                <td><Icons.FaCheck/></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td><Icons.FaCheck/></td>
                <td><Icons.FaCheck/></td>
                <td></td>
                <td></td>
                <td></td>
                <td>4</td>
              </tr>
              <tr>
                <td>25</td>
                <td>Graph Theory</td>
                <td></td>
                <td><Icons.FaCheck/></td>
                <td><Icons.FaCheck/></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td>2</td>
              </tr>
              <tr>
                <td>26</td>
                <td>Artificial Intelligence</td>
                <td><Icons.FaCheck/></td>
                <td><Icons.FaCheck/></td>
                <td><Icons.FaCheck/></td>
                <td><Icons.FaCheck/></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td>4</td>
              </tr>
              <tr>
                <td>27</td>
                <td>Computer Networks</td>
                <td></td>
                <td><Icons.FaCheck/></td>
                <td></td>
                <td><Icons.FaCheck/></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td><Icons.FaCheck/></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td>3</td>
              </tr>
              <tr>
                <td>28</td>
                <td>Visual Programming</td>
                <td></td>
                <td></td>
                <td><Icons.FaCheck/></td>
                <td><Icons.FaCheck/></td>
                <td></td>
                <td></td>
                <td><Icons.FaCheck/></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td>3</td>
              </tr>
              <tr>
                <td>29</td>
                <td>Computer Vision</td>
                <td><Icons.FaCheck/></td>
                <td><Icons.FaCheck/></td>
                <td></td>
                <td><Icons.FaCheck/></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td>3</td>
              </tr>
              <tr>
                <td>30</td>
                <td>Technical & Business Writing</td>
                <td><Icons.FaCheck/></td>
                <td><Icons.FaCheck/></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td><Icons.FaCheck/></td>
                <td><Icons.FaCheck/></td>
                <td></td>
                <td></td>
                <td></td>
                <td>4</td>
              </tr>
              <tr>
                <td>31</td>
                <td>Numerical Computing</td>
                <td></td>
                <td><Icons.FaCheck/></td>
                <td><Icons.FaCheck/></td>
                <td></td>
                <td></td>
                <td><Icons.FaCheck/></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td>3</td>
              </tr>
              <tr>
                <td>32</td>
                <td>Human Computer Interaction</td>
                <td><Icons.FaCheck/></td>
                <td><Icons.FaCheck/></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td><Icons.FaCheck/></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td>3</td>
              </tr>
              <tr>
                <td>33</td>
                <td>Final Year Project - I</td>
                <td><Icons.FaCheck/></td>
                <td><Icons.FaCheck/></td>
                <td><Icons.FaCheck/></td>
                <td><Icons.FaCheck/></td>
                <td><Icons.FaCheck/></td>
                <td><Icons.FaCheck/></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td><Icons.FaCheck/></td>
                <td><Icons.FaCheck/></td>
                <td></td>
                <td></td>
                <td></td>
                <td>8</td>
              </tr>
              <tr>
                <td>34</td>
                <td>Introduction to Business</td>
                <td><Icons.FaCheck/></td>
                <td><Icons.FaCheck/></td>
                <td></td>
                <td><Icons.FaCheck/></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td>3</td>
              </tr>
              <tr>
                <td>35</td>
                <td>Parallel & Distriuted Computing</td>
                <td></td>
                <td><Icons.FaCheck/></td>
                <td><Icons.FaCheck/></td>
                <td><Icons.FaCheck/></td>
                <td><Icons.FaCheck/></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td>4</td>
              </tr>
              <tr>
                <td>36</td>
                <td>Pakistan Studies</td>
                <td><Icons.FaCheck/></td>
                <td></td>
                <td></td>
                <td><Icons.FaCheck/></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td><Icons.FaCheck/></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td>3</td>
              </tr>
              <tr>
                <td>37</td>
                <td>Mobile App Development</td>
                <td></td>
                <td></td>
                <td><Icons.FaCheck/></td>
                <td><Icons.FaCheck/></td>
                <td><Icons.FaCheck/></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td>3</td>
              </tr>
              <tr>
                <td>38</td>
                <td>Entrepreneur & Leadership Skills</td>
                <td></td>
                <td></td>
                <td></td>
                <td><Icons.FaCheck/></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td><Icons.FaCheck/></td>
                <td><Icons.FaCheck/></td>
                <td></td>
                <td></td>
                <td></td>
                <td>2</td>
              </tr>
              <tr>
                <td>39</td>
                <td>Final Year Project - II</td>
                <td><Icons.FaCheck/></td>
                <td><Icons.FaCheck/></td>
                <td><Icons.FaCheck/></td>
                <td><Icons.FaCheck/></td>
                <td><Icons.FaCheck/></td>
                <td><Icons.FaCheck/></td>
                <td></td>
                <td></td>
                <td><Icons.FaCheck/></td>
                <td></td>
                <td><Icons.FaCheck/></td>
                <td></td>
                <td></td>
                <td></td>
                <td><Icons.FaCheck/></td>
                <td></td>
                <td></td>
                <td></td>
                <td>9</td>
              </tr>
              <tr>
                <td>40</td>
                <td>Information Security</td>
                <td></td>
                <td><Icons.FaCheck/></td>
                <td><Icons.FaCheck/></td>
                <td></td>
                <td><Icons.FaCheck/></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td>3</td>
              </tr>
              <tr>
                <td>41</td>
                <td>Islamic Studies/Ethics</td>
                <td><Icons.FaCheck/></td>
                <td></td>
                <td></td>
                <td><Icons.FaCheck/></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td><Icons.FaCheck/></td>
                <td><Icons.FaCheck/></td>
                <td></td>
                <td></td>
                <td></td>
                <td>4</td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </>
  )
}

export default CLOSINFO;