export const routeNameCONST = {
  course_information: "/course_information",
  closinfo: "/closinfo",
  plosinfo: "/plosinfo",
  departments: "/departments",
  semesters: "/semesters",
  courses: "/courses",
  assessment_tasks: "/assessment_tasks",
  plos: "/plos",
  clos: "/clos",
  questions: "/questions",
  qmapclo: "/qmapclo",
  enrollment: "/enrollment",
  results: "/results",
  sign_in: "/sign_in",
  adminSignUp: "/sign_up",
  enrollmentNewEnrollment: "/enrollment/newEnrollment",
  semestersNewSemester: "/semesters/newSemester",
  coursesNewCourse: "/courses/newCourse",
  assessmentTasksNewAssessment: "/assessment_tasks/newAssessment",
  plosNewPLO: "/plos/newPLO",
  closNewCLO: "/clos/newCLO",
  questionsNewQuestion: "/questions/newQuestion",
  qmapcloNewQMapCLO: "/qmapclo/newQMapCLO",
};

export const AUTH_TOKEN = {
  Type: "Token",
  Name: "auth-token-obe",
};
